# Generated by Django 4.1 on 2025-09-12 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(
                        max_length=100)), ('body', models.CharField(
                            max_length=255)), ('author', models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), ], options={
                'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts', }, ), ]
