# Generated by Django 5.2.6 on 2025-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="safe_for_work",
            field=models.BooleanField(default=True),
        ),
    ]
