# Generated by Django 5.2.6 on 2025-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_safe_for_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/images/%Y/%m/%d/"
            ),
        ),
    ]
