# Generated by Django 5.2.6 on 2025-10-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_like_remove_usertag_inuque_user_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="premium",
            field=models.BooleanField(default=False),
        ),
    ]
